service: satellite-tracker
frameworkVersion: '>2.0.0'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-north-1
  memorySize: 128

package:
  exclude:
    - ./**
  include:
    - ./satellite_tracker/**

functions:
  satellite_tracker:
    handler: satellite_tracker/index.handler
    events:
      - http:
          path: window
          method: post
