AWSTemplateFormatVersion: "2010-09-09"
Description: "NASA Space Apps 2020 - Can You Hear Me Now?"

Resources:
  MarsData:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: 
        "Fn::Sub": "${AWS::StackName}-mars-bucket"
        
  MarsRouterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "Mars Router Security Group"
      GroupName: "MarsRouterSecurityGroup"
      SecurityGroupIngress: 
        - Description: "Allow Inbound Traffic HTTP"
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
        - Description: "Allow Inbound Traffic SSH"
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
        - Description: "Allow Inbound Traffic ICMP"
          IpProtocol: icmp
          CidrIp: 0.0.0.0/0
          FromPort: -1
          ToPort: -1

  ESAArchiveSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "ESA Archive Security Group"
      GroupName: "ESAArchiveSecurityGroup"
      SecurityGroupIngress: 
        - Description: "Allow Inbound Traffic HTTP"
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
        - Description: "Allow Inbound Traffic SSH"
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
        - Description: "Allow Inbound Traffic ICMP"
          IpProtocol: icmp
          CidrIp: 0.0.0.0/0
          FromPort: -1
          ToPort: -1

  SatelliteTrackerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "Satellite Tracker Security Group"
      GroupName: "SatelliteTrackerecurityGroup"
      SecurityGroupIngress: 
        - Description: "Allow Inbound Traffic HTTP"
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
        - Description: "Allow Inbound Traffic SSH"
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
        - Description: "Allow Inbound Traffic ICMP"
          IpProtocol: icmp
          CidrIp: 0.0.0.0/0
          FromPort: -1
          ToPort: -1

  InstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "EC2SSMRole"
      Description: "Allows SSM to attach to EC2"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: SSMInstanceProfile
      Roles:
        - !Ref InstanceProfileRole

  MarsRouter:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t3.micro
      ImageId: ami-008dea09a148cea39
      IamInstanceProfile: !Ref InstanceProfile
      SecurityGroupIds: 
        - !Ref MarsRouterSecurityGroup
      Tags:
        - Key: "Name"
          Value: "Mars Router"
      KeyName: nasa-spaceapps-2020
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo hostnamectl set-hostname mars-router
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y npm curl bash ca-certificates openssl coreutils python2 python3 make gcc g++ grep util-linux binutils findutils

  ESAArchive:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t3.micro
      ImageId: ami-008dea09a148cea39
      IamInstanceProfile: !Ref InstanceProfile
      SecurityGroupIds: 
        - !Ref ESAArchiveSecurityGroup
      Tags:
        - Key: "Name"
          Value: "ESA Archive"
      KeyName: nasa-spaceapps-2020
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo hostnamectl set-hostname esa-archive
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y npm curl bash ca-certificates openssl coreutils python2 python3 make gcc g++ grep util-linux binutils findutils

  SatelliteTracker:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t3.micro
      ImageId: ami-008dea09a148cea39
      IamInstanceProfile: !Ref InstanceProfile
      SecurityGroupIds: 
        - !Ref SatelliteTrackerSecurityGroup
      Tags:
        - Key: "Name"
          Value: "Satellite Tracker"
      KeyName: nasa-spaceapps-2020
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo hostnamectl set-hostname satellite-tracker
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y npm curl bash ca-certificates openssl coreutils python2 python3 make gcc g++ grep util-linux binutils findutils

  MarsRouterIP:
    Type: AWS::EC2::EIP
    Properties: 
      InstanceId: !Ref MarsRouter

  ESAArchiveIP:
    Type: AWS::EC2::EIP
    Properties: 
      InstanceId: !Ref ESAArchive

  SatelliteTrackerIP:
    Type: AWS::EC2::EIP
    Properties: 
      InstanceId: !Ref SatelliteTracker
